<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- sensor-->
    <joint name="sensor" type="fixed">
        <parent link="wheel_direct_link"/>
        <child link="sensor_link"/>
        <origin xyz="0 0 ${main_block_height}"/>
    </joint>

    <link name="sensor_link">
        <visual>
            <geometry>
                <cylinder length="${sensor_height}" radius="${sensor_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${sensor_height}" radius="${sensor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.05" length="${sensor_height}" radius="${sensor_radius}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

     <gazebo reference="sensor_link">
        <material>Gazebo/Orange</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>100</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>20.0</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>sensor_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>


     <!-- head_sensor-->
    <joint name="head_sensor" type="fixed">
        <parent link="sensor_link"/>
        <child link="head_sensor"/>
        <origin xyz="0 0 ${sensor_height/2}"/>
    </joint>

    <link name="head_sensor">
        <visual>
            <geometry>
                <cylinder length="${sensor_height-0.01}" radius="${sensor_radius+0.02}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${sensor_height-0.01}" radius="${sensor_radius+0.02}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.02" length="${sensor_height-0.2}" radius="${sensor_radius+0.1}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="head_sensor">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>