<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- global variable -->
    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_size" value="0.03" />
    <xacro:property name="main_block_height" value="0.096"/>
    <xacro:property name="main_block_radius" value="0.1725"/>
    <xacro:property name="sensor_height" value="${wheel_size-0.01}"/>
    <xacro:property name="sensor_radius" value="${wheel_radius/2}"/>

    <material name="white"> 
        <color rgba="1 1 1 1" />   
    
    </material>
    
    <material name="blue"> 
        <color rgba="0 0 1 1" />  
    
    </material>

    <material name="black"> 
        <color rgba="0 0 0 1" />   
    
    </material>

    <material name="orange"> 
        <color rgba="1 0.3 0.1 1" />   
    
    </material>

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro> 

     <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  
    
</robot>